data_dir: data/unified
nlq_val_anno: data/nlq_v2/nlq_val.json
nlq_train_anno: /data/datasets/ego4d_data/v2/annotations/nlq_train.json
feature_type: egovlp_internvideo
feature_dim: 2304
max_v_len: 1200

qa_train_splits: []
nlq_train_splits: ['NLQ_train']
test_splits: ['QaEgo4D_test', 'QaEgo4D_test_close', 'NLQ_val']
closeqa_weight: 50

tokenizer_path: google/flan-t5-small

num_workers: 4
batch_size: 16

env_feature:
  env_feature_path: '/data/soyeonhong/GroundVQA/env_feature/102720/captions'
  sbert_q_feat_path: '/data/soyeonhong/GroundVQA/env_feature/102720/queries'
  env_feature_type: 'llava_caption'
  subset: False
  object: False
  one_set: False